---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[application_play::opsworks_setup]
      - recipe[application_play::opsworks_configure]
      - recipe[application_play::opsworks_deploy]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: {}
    data_bags_path: test/data_bags
